version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./docker-data/mongo/data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 5100:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    links:
      - mongo
    depends_on:
      - mongo

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./docker-data/mariadb/config:/etc/mysql/conf.d
      - ./docker-data/mariadb/data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  back:
    # image: pm2:v1
    build: ./docker-data/back
    container_name: visual_back
    ports:
      - "3000:3000"
    volumes:
      - ./docker-data/back:/project
    depends_on:
      - mongo
      - mariadb

  front:
    image: nginx
    container_name: visual_front
    restart: always
    ports:
      - "3001:80"

    volumes:
      - ./docker-data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-data/nginx/html:/usr/share/nginx/html
